### ISSUE TITLE
Search for relevant documents based on existing ones

### ISSUE THREAD

**Issue by ShengjieZhou** [Hypertopic/HyperGlosae#10]
Consult the different translations, commentaries, analyses of a given source based on Google Search or Wiki

**Comment by kemplail** [comment]
Cette user story est peut être un peu trop large, car selon le type de document recherché (traductions, commentaires...) il est possible que la recherche et la consultation de ces éléments se fasse de manière différente, et ça pourrait donc demander des user stories différentes. Sinon je pense qu'elle respecte tous les autres critères.

**Comment by benel** [comment]
Is that a kind of integration with third party applications?

**Comment by benel** [comment]
Thank you for your suggestion @ShengjieZhou. 
I am not sure to understand it... Is that a kind of integration with third party applications?

**Comment by ShengjieZhou** [comment]
> Thank you for your suggestion @ShengjieZhou. I am not sure to understand it... Is that a kind of integration with third party applications?

I'm sorry I didn't express my opinion correctly. My idea is to consult references within existing documents. When the user clicks on the hyperlink of the referenced document, whose information will be displayed on the right-hand side (author information, comments and a link to Wikipedia or the original text)

**Comment by benel** [comment]
@ShengjieZhou Hmm... I'm still not sure this feature fits with the "production vision".
