### ISSUE TITLE
Years of first issue should not be displayed as 1970

### ISSUE THREAD

**Issue by benel** [Hypertopic/HyperGlosae#100]
`dc_issued` metadata works fine with `2023-05-04T12:22:20.315Z` as well as with `04/05/2023`. They are displayed as `2023`.
However it doesn't work with `2023` which is displayed as `1970`.

## Workaround

Type:
```
dc_issued: "2023"
```
instead of:
```
dc_issued: 2023
```

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Implementation strategy
#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation
### Phase 3
- [ ] Screencast

**Comment by jeromeBRM** [comment]
Dans le contexte de l'histoire du cinéma, la date de l'œuvre et de ses interprétations sont importantes car il s'agit souvent d'œuvre ancienne.

**Comment by koeltv** [comment]
https://github.com/Hypertopic/HyperGlosae/blob/1c2432bee72407082f6cbe7baed4e3a063fcb417/features/edit_glose_metadata.feature#L7-L38

Il faudrait retirer les guillemets sur les années (`dc_issued`) pour provoquer l'erreur d'enregistrement de l'année et ajouter une conséquence pour les scénarios pour vérifier que les métadonnées ont bien été prise en compte.

```
Alors ...
Et les métadonnées ont bien été prises en comptes
```
