### ISSUE TITLE
Filter comments with timecode thank to a tag

### ISSUE THREAD

**Issue by AVCharpentier** [Hypertopic/HyperGlosae#105]
Avec cette fonctionnalité, les utilisateurs seront capables de faire une recherche/tri sur des commentaires d'une vidéo à partir de tag. En effet, il pourra trouver les commentaires les plus pertinents d'une vidéo afin de repérer efficacement un passage précis de la scène.

L'utilisateur veut réduire le nombre de commentaires pour seulement voir celui qui l'intéresse.

Si un utilisateur recherche à annoter un film en entier, le nombre de commentaires peut alors être conséquent et difficile de s'y retrouver. Cette fonctionnalité permettrait donc de faciliter la recherche de l'information qui lui est utile.

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [ ] Implementation strategy

#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

### Phase 3
- [ ] Screencast

**Comment by AVCharpentier** [comment]
# Mockups
Nous avons créé des maquettes pour démontrer le fonctionnement de notre nouvelle fonctionnalité de filtrage des commentaires basée sur des mots-clés. 

## Maquette n°1
La première maquette met en avant l'utilisation d'un champ de texte, dans lequel l'utilisateur peut entrer le mot spécifique qu'il souhaite rechercher. Une fois le mot saisi, notre système analyse les commentaires disponibles et filtre ceux qui contiennent ce mot, permettant ainsi à l'utilisateur de visualiser uniquement les commentaires pertinents à sa recherche.

![Screenshot_8](https://github.com/Hypertopic/HyperGlosae/assets/95986857/c5a10621-5328-4372-9f5e-3fa22f2c6362)



## Maquette n°2
La deuxième maquette propose une approche différente en offrant à l'utilisateur une liste de mots-clés préétablis ou que le programme doit être capable d'identifier.  L'utilisateur peut sélectionner un ou plusieurs mots-clés parmi ceux proposés, et notre système effectue le filtrage en fonction de ces choix. 

![Screenshot_9](https://github.com/Hypertopic/HyperGlosae/assets/95986857/52e3330a-acfd-42e1-8776-7a0752a64012)


### Notre choix

Nous avons pris la décision de nous baser sur la première approche en utilisant un champ de texte pour plusieurs raisons. 
-  Les mots-clés peuvent évoluer avec le temps. En utilisant un champ de texte, nous permettons à l'utilisateur de saisir librement le mot-clé qu'il souhaite rechercher, offrant ainsi une flexibilité dans la recherche.
- Si on propose des mots clés, l'utilisateur risque de mettre un certain temps avant de trouver celui qui lui convient du fait du nombre important de proposition de mot clés. 
- Avec la solution n°2, il se poserait également la question de l'identification des mots-clés : préétablis, à identifier dynamiquement (en fonction de la longueur des mots, ...), ... ?

**Comment by AVCharpentier** [comment]
Nous allons rencontrer ***des problèmes*** en lien avec le ***mode édition***. 

Si l'utilisateur clic sur le champ texte pour effectuer ça recherche, le document dans la glose va passer en mode édition ce qui va empêcher l'utilisateur de pouvoir saisir ces mots.

Ceci va sûrement poser problème pour un autre ticket #74 Qui permet de modifier le timecode de la vidéo suite à un clic sur un commentaire.

**Comment by benel** [comment]
Tags are indeed an important topic for document management systems. However this topic is more difficult than what it seems. Related features could be planned in the future but not without a deep analysis and design work.
