### ISSUE TITLE
Predefined types should be the stored in the database

### ISSUE THREAD

**Issue by julien-millour** [Hypertopic/HyperGlosae#107]
Currently, those types are set in the frontend code. They should be moved to the database in a specific document. 

Phase 1

- [x] Implementation strategy (ALL)

Phase 2

- [x] Implementation (ALL)
- [x] Acceptance tests (Capybara)

**Comment by julien-millour** [comment]
Drawing explaining how the changed would be implemented

![Image](https://github.com/Hypertopic/HyperGlosae/assets/126160064/fc76895d-931c-404c-8808-536ac6e2ecd7)

**Comment by Rochijr** [comment]
Below a drawing about how the actual reduce works:
https://media.discordapp.net/attachments/1086200997824704552/1114088995446595685/20230602_091120.jpg?width=901&height=676

**Comment by julien-millour** [comment]
- [ ] Acceptance tests (Capybara) (Corentin, Majed et Antoine)
- [ ] Fixing git history (Romain et Julien)
