### ISSUE TITLE
Display the history of the branches crossed

### ISSUE THREAD

**Issue by MCtzr** [Hypertopic/HyperGlosae#117]
When user is navigating inside a collection, the user should have access to the history of the last branches he crossed.

If the user didn't crossed any branch before being inside a collection, the history isn't displayed.

![Image](https://github.com/Hypertopic/HyperGlosae/assets/91234392/59380966-3ba6-4862-b161-0d295d86059c)

This feature is related to #108

**Comment by benel** [comment]
Mobile browsing should be kept out of the scope of this application (see #142).
