### ISSUE TITLE
Display all articles in a tree view

### ISSUE THREAD

**Issue by Ziwei-GONG-UTT** [Hypertopic/HyperGlosae#12]
Habituellement, il y a un article d'origine et les autres articles sont ses sous-articles. Lorsqu'il s'agit d'un très grand nombre de sous-postes ou lorsque des sous-sous-postes apparaissent, une table des matières est nécessaire pour permettre aux utilisateurs de sélectionner plus rapidement l'article auquel ils doivent accéder. Il est également possible de mieux voir les relations entre les textes.

Plus loin, nous pouvons supprimer ou ajouter de nouveaux articles plus rapidement dans cet arbre

**Comment by AmalCHIKHAOUI** [comment]
on comprends tout juste du titre donc c'est très bien clair , ça respecte les critères

**Comment by benel** [comment]
Similaire à #11.

**Comment by benel** [comment]
Cette suggestion est similaire à la #11. 
@Ziwei-GONG-UTT, si vous voulez bien fermer votre ticket (#12). Merci d'avance.
