### ISSUE TITLE
license should be displayed as a logo instead of name

### ISSUE THREAD

**Issue by AVCharpentier** [Hypertopic/HyperGlosae#129]
#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation
### Phase 3
- [ ] Screencast

**Comment by astrid-devericourt** [comment]
## Stratégie d'implémentation

2. 1. Nous allons utiliser les images sur ce site en récupérant les url dans l'inspecteur :https://creativecommons.org/about/cclicenses/
On obtient les logo des licences, par exemple : https://licensebuttons.net/l/by/3.0/88x31.png

2. Dans le composant Metadata.js, modifier la fonction License ligne 72 en précisant l'url précédente qu'il faudra modifier en fonction de la valeur de licence name.

**Comment by benel** [comment]
Merged as c8590b3115a2a03600db42b6a50f34f46cbeb634.
