### ISSUE TITLE
Set the article to ignore (not visible)

### ISSUE THREAD

**Issue by Ziwei-GONG-UTT** [Hypertopic/HyperGlosae#13]
Permet aux utilisateurs de masquer le contenu qu'ils ne trouvent pas utile ou qu'ils ne veulent pas voir, pour une meilleure expérience de lecture.

**Comment by StachoB** [comment]
Ticket qui pourrait être redécoupé pour respecter le principe "small", en deux parties : ignoré et lu.

**Comment by benel** [comment]
Merci pour votre suggestion @Ziwei-GONG-UTT.
Vous devriez probablement suivre les conseils de vos camarades et découper votre fonctionnalité en plusieurs.

**Comment by benel** [comment]
@Ziwei-GONG-UTT Something like `Ignore document`?

**Comment by benel** [comment]
No more necessary with #149.
