### ISSUE TITLE
On mobile, navigating between collections should not reset progress on previous collection

### ISSUE THREAD

**Issue by adrienfallot** [Hypertopic/HyperGlosae#137]
# Reproduction scenario

1. On mobile, go here: https://d1h122cknc6elf.cloudfront.net/collection/1451decd-68ad-406f-9293-f86d59fc725c/document/e5a92c28-0699-11ee-a942-367ddac73ffe
2. Go to document 4 above 20
3. Go to "Parcours : Nicolas de Myre, évêque et confesseur (Adrien Fallot),2023, All rights reserved".
4. Go back to "Parcours : Découverte de l'Église Saint-Nicolas, Troyes, Aube (Adrien Fallot),2023, All rights reserved".

The expected result should be to return to document 4 via 20, not the first, when returning to the previous collection at step 4.

**Comment by benel** [comment]
Mobile browsing should be kept out of the scope of this application (see #142).
