### ISSUE TITLE
A document may refer to a non a existing document

### ISSUE THREAD

**Issue by benel** [Hypertopic/HyperGlosae#138]
Displaying a document that includes a non existing document results in the following exception being raised:

    TypeError: null is not an object (evaluating 'x._id')

**Comment by GwenRiou** [comment]
Created page for 404 error

**Comment by benel** [comment]
@GwenRiou Thank you for your mockup.
I think however that the issue your project is interested in is #115 rather than this one. 

This issue (138) relates with the case when the focused document *does* exist (in the center of the interface) but refers to a non-existing document (in the left margin).

**Comment by benel** [comment]
This bug has been experienced by a student of @jfalip after deleting a non terminal document.
