### ISSUE TITLE
Update an existing reference

### ISSUE THREAD

**Issue by AVCharpentier** [Hypertopic/HyperGlosae#14]
Si un utilisateur se rend compte qu'une référence est erronée, il devrait alors être capable de modifier cette référence par une nouvelle.

**Comment by Rochijr** [comment]
Cela me paraît clair et en adéquation avec les principes INVEST sauf éventuellement Independent.

Si on considère qu'il faut avoir l'autorisation de l'auteur pour modifier/mettre à jour les liens du documents, je pense que cela implique une dépendance avoir une autre fonctionnalité.

**Comment by AmalCHIKHAOUI** [comment]
Ce ticket peut être dépendant d’autres fonctionnalités, dans ce cas il correspondant pas au critère indépendant

**Comment by benel** [comment]
@AVCharpentier En quoi cette fonctionnalité serait-elle différente de la suppression de la référence #3 suivie de la création d'une nouvelle #1 ?
