### ISSUE TITLE
Documents created from scratch should be editable

### ISSUE THREAD

**Issue by benel** [Hypertopic/HyperGlosae#145]
In a **page**, the **focused part** (in the middle) is the one to be read, while the margin (on the right) is to be written.

The problem is that documents created from scratch, because they don't have reference, can never be in the right margin and hence can never be edited.

There could be two options for designing this fix:
- either the central part is made editable (but when should be authorize edition or not ?)
- or the document is created as a glose of "nothing".

## Workaround

For now, an additional blank document is created every time we need to create a document from scratch.

#### Phase 1
- [x] Scenarios (Gherkin)
- [ ] ~~Mockups~~
- [x] Implementation strategy
#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation
### Phase 3
- [x] Screencast

**Comment by nitram35** [comment]
En IF14, on commence from scracth, fix le bug serait donc un option à envisager

**Comment by antooinex** [comment]
We want the ability for the end-user to be able to edit the document they're currently reading. This way they can add information to the document, fix a typo or simply update the document. This principle is particularly important in ethnography since the users often tend to update documents and make annotations.

**Comment by nitram35** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/105852593/162eafba-f3ff-4dbd-a390-9f06ca0a5bc1)

**Comment by GwenRiou** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/74981788/bfbff509-5a65-499d-9854-4b630f4fb417)

**Comment by benel** [comment]
Thank you for your contribution @Anto792 @AliceGuib @koeltv!

Don't forget to create a (draft) pull request so that we can discuss about your implementation and so that I can help you if needed.

**Comment by Anto792** [comment]
@AliceGuib @Anto792 

https://github.com/Hypertopic/HyperGlosae/assets/70704575/6a9f7d85-967c-4fee-af38-f185bca052f0
