### ISSUE TITLE
Succeeding and failing updates should not be displayed the same

### ISSUE THREAD

**Issue by benel** [Hypertopic/HyperGlosae#147]
For now, when authentication or authorization fails, a warning is shown but the (new and unsaved) state is displayed.

This fix should be designed carefully so that:
- users cannot think that the new state is saved,
- users do not loose the new data,
- users might log with a different account to proceed with saving data.

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Implementation strategy
#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation
### Phase 3
- [ ] Screencast

**Comment by antooinex** [comment]
#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Implementation strategy
#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation
### Phase 3
- [ ] Screencast

**Comment by KoffiBalayn** [comment]
https://github.com/Hypertopic/HyperGlosae/assets/160734127/ca2a1066-dbcc-49d5-a911-8598fed01f2d
