### ISSUE TITLE
Add a document created by other to one's bookshelf

### ISSUE THREAD

**Issue by benel** [Hypertopic/HyperGlosae#150]
This feature would be needed once #149 is implemented.

**Comment by EnzoSimonoviciUTT** [comment]
Je trouve pertinent l'idée de pouvoir ajouter une interprétation venant d'autrui à propos d'une oeuvre cinématographique

**Comment by vernet-william** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/72734082/59d60bdf-d117-4fbd-9be2-4bd8e058c7e9)
