### ISSUE TITLE
Add a censorship system

### ISSUE THREAD

**Issue by ToGoSleep** [Hypertopic/HyperGlosae#152]
Vu que tous les élèves peuvent commenter, il se peut qu'ils utilisent des mots vulgaires, dans ce cas la ces mots doivent être censurés

Par exemple :

Un gros mot sera transformé en "****"

La censure est importante surtout quand c'est public et que tout le monde peut voir.

Cependant le système a ses limites

**Comment by benel** [comment]
@ToGoSleep Please translate the title of your ticket in English.

Please note that a feature should be phrased as a verb (an action) done by the user.
But I suppose it would be difficult for your ticket. It may be a **requirement** instead.
