### ISSUE TITLE
The timecode should refer to the right extract of the video

### ISSUE THREAD

**Issue by vernet-william** [Hypertopic/HyperGlosae#154]
La première utilisation des timecodes renvoie le bon extrait de la vidéo.
Cependant, les utilisations suivantes renvoie vers le mauvais extrait de la vidéo (ca recule à chaque utilisation).

**Comment by EnzoSimonoviciUTT** [comment]
#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Implementation strategy
#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation
### Phase 3
- [ ] Screencast

**Comment by benel** [comment]
Thank you very much for your scenario and test @EnzoSimonoviciUTT, @jeromeBRM, @ToGoSleep, @vernet-william.

Please write a comment in this discussion in which you will explain: 

1. why you could not reproduce the bug programmatically,
2. why you could not write an implementation strategy (or could you?),
3. why you could not write an implementation.

This is important to document it for people who will face this bug again.

**Comment by benel** [comment]
I did not manage to reproduce the bug. Hence I close the ticket for now.

If you do succeed in reproducing the bug, please describe the steps (on YouTube and Hyperglosae) below and I will reopen it.
