### ISSUE TITLE
Create comment from a fragment of a document

### ISSUE THREAD

**Issue by KoffiBalayn** [Hypertopic/HyperGlosae#156]
![image](https://github.com/Hypertopic/HyperGlosae/assets/160734127/8df65756-031a-417c-a794-f4a6d0a28cd5)

Highlight a part of text and click on a button to create a code for this extract. Highlighted text will be automatically rewritten. The featured is on only when a glose is created.

**Comment by GwenRiou** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/74981788/7cae2030-6a0c-4a99-9343-d1c3b397feea)

**Comment by GwenRiou** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/74981788/2142927a-8a2c-4d6d-beb1-669f93402bb5)

**Comment by GwenRiou** [comment]
Phase 1

- [ ] Mockup
- [ ] Scenarios (Gherkin)
- [ ] Implementation strategy

Phase 2

- [ ] Acceptance tests (Capybara)
- [ ] Implementation

Phase 3

- [ ] Screencast

**Comment by KoffiBalayn** [comment]
After the meeting with stakeholder, it would be more appropriate to have only the "Etiquette" on the glose and not the text fragment. In order to see what "Etiquette" corresponds to text fragment, by hovering the "etiquette" with the cursor, it will highlight the text fragment on the focus document.

Modified mockup : 


![Image](https://github.com/Hypertopic/HyperGlosae/assets/160734127/f67fdc30-a706-4238-bdba-5927cb4e3f7d)
![Image](https://github.com/Hypertopic/HyperGlosae/assets/160734127/b3abd21d-e6bd-439c-b686-4d3894681465)

**Comment by GwenRiou** [comment]
The filed that will be change are :
 - Passage.js --> the PassageSource function for the formattedText and the PassageMargin function for the EditableText
 - FormattedText.js
 - EditableText.js

The future code should be able to detect highlight text, we can use this [react-highlight](https://github.com/ydeshayes/react-highlight) library. or use the event onMouseUpCapture={this.selectedText}

**Comment by GwenRiou** [comment]
Changement de la constante beingEdited et setBeingEdited de EditableText.js vers Passage.js pour pouvoir changer l'état édition de la glose à partir du passage. Et passe la funciton createdComment dans Passage.js vers FormattedText.js et PassageSource.js pour quelle puisse être appeler.

**Comment by antooinex** [comment]
> Split the issue into multiple features, create a minimal version first

Created a new issue to separate the creation of a comment and the highlighting of a fragment of text (once a comment was created) : https://github.com/Hypertopic/HyperGlosae/issues/180

**Comment by GwenRiou** [comment]
https://github.com/Hypertopic/HyperGlosae/assets/74981788/808562e1-b303-47ea-a9da-2da9e9d26820

Screencast made with Fluorite-Eyes

**Comment by mbel-jordan** [comment]
https://github.com/Hypertopic/HyperGlosae/assets/79590372/e4ac293e-1c40-4511-bf01-44d7635d835a

**Comment by benel** [comment]
Thank you for your screencast @mbel-jordan.

@KoffiBalayn @GwenRiou @antooinex @Fluorite-Eyes @mbel-jordan 
For the final video, don't forget to create passages first, so that comments are aligned with the source.
