### ISSUE TITLE
Group a set of document under a large project set

### ISSUE THREAD

**Issue by GagatheRollex** [Hypertopic/HyperGlosae#16]
Cette fonctionnalité permettrait de grouper un ensemble de documents (nommé "projet"). De cette manière, il serait possible de relier, grâce à un lien hypertexte, un document à un ensemble "projet". Ainsi dans le cas où un document serait une étude annexe d'un projet (composé lui-même de plusieurs documents reliés les uns aux autres), la source du documents serait le projet complet.

**Comment by marina-pera** [comment]
Cette fonctionnalité semble être trop vague par rapport à "a large project set".

**Comment by AmalCHIKHAOUI** [comment]
Ce ticket ne respecte pas le critère suffisamment petit
