### ISSUE TITLE
A glose block with missing annotations (or none) should be editable

### ISSUE THREAD

**Issue by raphaelweis** [Hypertopic/HyperGlosae#161]
After creating a document, it becomes impossible to create additional annotations to the side of the main glose without creating an additional glose.

![image](https://github.com/Hypertopic/HyperGlosae/assets/111392195/398c9536-7832-435a-b636-1e1d0cfb728e)

**Comment by nitram35** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/105852593/258dd901-5fd6-4e81-a7b6-b237ed7374da)

**Comment by nitram35** [comment]
#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Mockups
- [ ] Implementation strategy
#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation
### Phase 3
- [ ] Screencast
