### ISSUE TITLE
Hide reference for a user

### ISSUE THREAD

**Issue by AVCharpentier** [Hypertopic/HyperGlosae#17]
Pour des questions de lisibilité, il se pourrait qu'un utilisateur décide de cacher des références précises.
Ceci permettrait à l'utilisateur de gagner de la place sur l'écran et de ne garder que les informations qui lui sont utiles.

Par exemple, l'utilisateur pourrait décider de cacher tous les documents qui ont pour référence le document en cours de lecture.

**Comment by GagatheRollex** [comment]
Cette proposition me semble correspondre aux contraintes INVEST des fonctionnalités. Il pourrais juste être précisé ce qui est attendu lorsqu'un lien est caché : est-ce qu'il disparait totalement ? Mais du coup comment faire l'action inverse et le remettre en place ?

**Comment by AmalCHIKHAOUI** [comment]
Ce ticket respecte les critères de INVEST

**Comment by benel** [comment]
@AVCharpentier Pendant combien de temps, cela resterait-il caché ? Tant qu'on est sur la page ? Tant qu'il s'agit de la même "session" (à définir) ? Pour toujours ? ....

**Comment by benel** [comment]
Similar to #20?
