### ISSUE TITLE
View document modification history

### ISSUE THREAD

**Issue by CorentinPARZ** [Hypertopic/HyperGlosae#18]
Since anyone can contribute to the content of HyperGlosae, it can be useful to see the evolution of the content over time

**Comment by AmalCHIKHAOUI** [comment]
Ce ticket me semble qu’il n’est pas suffisamment petit

**Comment by benel** [comment]
@CorentinPARZ You should probably split the part concerning the log (who did what and when) and the part concerning the former content.

**Comment by CorentinPARZ** [comment]
Done
- https://github.com/Hypertopic/HyperGlosae/issues/33
- https://github.com/Hypertopic/HyperGlosae/issues/34

**Comment by lililiane** [comment]
Arts plastiques : Cela nous permet de comprendre la construction du document

**Comment by benel** [comment]
Thanks for splitting the ticket.
