### ISSUE TITLE
Highlight a commented fragment of text

### ISSUE THREAD

**Issue by antooinex** [Hypertopic/HyperGlosae#180]
When a fragment of text has been commented in a glose, hovering the comment in the glose should highlight the fragment of text in the document.

**Comment by antooinex** [comment]
Phase 1

- [ ] Mockup
- [ ] Scenarios (Gherkin)
- [ ] Implementation strategy

Phase 2

- [ ] Acceptance tests (Capybara)
- [ ] Implementation

Phase 3

- [ ] Screencast

**Comment by KoffiBalayn** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/160734127/ec15da76-a846-48b1-b454-b680bf96de8c)

**Comment by KoffiBalayn** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/160734127/aaed8fa4-e6c8-4572-8105-3b5498d5e1fc)

**Comment by GwenRiou** [comment]
https://github.com/Hypertopic/HyperGlosae/assets/74981788/98d2ef8e-4c9b-44fc-a099-254d4bc46743

**Comment by GwenRiou** [comment]
https://github.com/Hypertopic/HyperGlosae/assets/74981788/bb6a1e7c-5ac5-4ad2-8e1a-9172e0564db7
