### ISSUE TITLE
A block may be replaced by a single-line text

### ISSUE THREAD

**Issue by AgatheIV** [Hypertopic/HyperGlosae#192]
**Dans le cas où on remplace le texte d'un paragraphe par un contenu d'au moins deux lignes** 

Le paragraphe original
![Picture1-1](https://github.com/Hypertopic/HyperGlosae/assets/119731198/09787894-a555-4e0d-aec7-90f4a0a707a4)

Le paragraphe en cours d'édition
![Picture1-2](https://github.com/Hypertopic/HyperGlosae/assets/119731198/951493df-6cd1-4903-8114-99f0c759fb48)

Le paragraphe une fois édité
![Picture1-3](https://github.com/Hypertopic/HyperGlosae/assets/119731198/67ba1fe5-0311-4015-b315-561f63218606)

**Dans le cas où on remplace le texte d'un paragraphe par un contenu d'une seule ligne**

Le paragraphe original
![Picture2-1](https://github.com/Hypertopic/HyperGlosae/assets/119731198/807185ce-aa18-4b1e-affc-9683dc006e5a)

Le paragraphe en cours d'édition
![Picture2-2](https://github.com/Hypertopic/HyperGlosae/assets/119731198/01d38632-998c-491b-ad18-d79cdee8304c)

Le paragraphe une fois édité (noté l'espace blanc supplémentaire qui apparait)
![Picture2-3](https://github.com/Hypertopic/HyperGlosae/assets/119731198/d021b7e8-b647-43f9-a3a1-d06cdc33f5f5)

Lorsqu'on réessaye d'éditer le paragraphe l'ensemble du texte de la glose apparait

![Picture2-4](https://github.com/Hypertopic/HyperGlosae/assets/119731198/cb26101e-df02-4f30-8544-a17790e74628)

**Comment by benel** [comment]
Bien vu @AgatheIV. Probablement une expression régulière qui est un peu trop stricte...

**Comment by benel** [comment]
Plutôt que de nommer le fix par ce que le logiciel ne sait pas faire, vous pourriez plutôt exprimer ce qu'il est possible d'avoir dans les données et donc qu'il faut prévoir (voir des [exemples](https://github.com/Hypertopic/HyperGlosae/issues?q=is%3Aissue+is%3Aopen+may+)).
