### ISSUE TITLE
Add new reference 

### ISSUE THREAD

**Issue by SebBac** [Hypertopic/HyperGlosae#2]
En tant qu’utilisateur, depuis une page, je souhaite pouvoir ajouter de nouvelles références vers d’autres documents.

Critères d’acceptations : depuis un document, je peux rajouter et enregistrer de nouvelles références.

Exemple de référence : 
![image](https://user-images.githubusercontent.com/73548842/225074989-0a3d648d-f3b4-4af0-a2d7-593dc9f1a9c6.png)

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation
### Phase 3
- [ ] Screencast

**Comment by AmalCHIKHAOUI** [comment]
Juste de titre c'est pas clair ou il faut rajouter la référence ou elle sert quoi

**Comment by benel** [comment]
@SebBac Le titre est peut-être suffisant, mais dans la description, il faudrait peut-être préciser ce que vous entendez par "référence".

**Comment by lililiane** [comment]
Art plastique : cette feature peut être utilisé pour ajouter la référence d'un dessin/tableau dans une collection/exposition

**Comment by MCtzr** [comment]
**Histoire de l'art** : Cette feature pourrait être intéressante pour notre projet. Cependant, celle-ci ne semble pas être une priorité. Notre partie prenante étant informaticien, ajouter des références à partir du Json ne lui posera peut être pas problème.

**Comment by RomainUTT** [comment]
Ethnométhodologie: This can be helpful to link our actions.

**Comment by khbgbgk1** [comment]
Préparation de l'implémentation:
ça touchera :
- au "lectern" : dans la colone : "sources" : Implémenter l'ajout d'une référence mère
- au "FutureDocument" :  créer un nouveau composant à l'image de "FutureDocument"
- 'Implémenter un système de recherche' afin de récupérer l'ID du glose père




Avec @koeltv

**Comment by Anto792** [comment]
Projet traduction 2024
[Maquette](https://www.figma.com/proto/tOV6vMWnpDldlhXUnwcBHF/Model?type=design&node-id=108-2&t=XUNX40qJATDSF19m-0&scaling=contain&page-id=109%3A2&starting-point-node-id=112%3A14) avec @PaulGitProject et @Anto792 
Première version 
![image](https://github.com/Hypertopic/HyperGlosae/assets/70704575/286ed939-8af3-4cd4-825f-61fe2e0ced03)
![image](https://github.com/Hypertopic/HyperGlosae/assets/70704575/d7197018-44cd-4b27-baf5-e922f6428753)
![image](https://github.com/Hypertopic/HyperGlosae/assets/70704575/a2eb3b41-a351-4d08-b8aa-69d1ada79de2)

**Comment by koeltv** [comment]
Quelques problèmes pour les tests, en effet l'ajout d'un nouveau bouton avec la classe 'create-document' rend certains tests ambigus, aussi des modifications ont du être appliqué du côté de Capybara pour les différencier.
Cependant il existait déjà une ambiguité entre le bouton sur la page d'accueil et celui sur le lectern qui n'avait aucun impact jusqu'ici ceux-ci étant sur des pages différentes, mais l'apparition d'un 3ème bouton nécessitait de faire la différence dans certains cas.

Schéma de mise à jour des commits:
`git stash > git reset hard SCENARIO > git unstash > git amend > git cherry-pick TEST > git unstash > git amend > git cherry-pick FEATURE > git unstash`
