### ISSUE TITLE
Hide 1 or multiple links 

### ISSUE THREAD

**Issue by marina-pera** [Hypertopic/HyperGlosae#20]
The user can be lost in translation when reading a text.
Hiding links will allow the user to hide the references to make, in some way, the reading easier.
 
It will be represented by a "hide button" an the top of the link and when closed, the box of the link will hide the text and only show a button to make the link reappear.

**Comment by AVCharpentier** [comment]
Il n'y a selon moi, pas trop de negotiation. Sinon les autres critères de INVEST sont respectés.

**Comment by julien-millour** [comment]
Cette fonctionnalité me semble respecter les principes INVEST.

**Comment by benel** [comment]
Similar to #17?
