### ISSUE TITLE
The new `setup.sh` file to quickly get started with the backend has `CRLF` line endings.

### ISSUE THREAD

**Issue by raphaelweis** [Hypertopic/HyperGlosae#202]
This is a problem because this file is a `.sh` file meant to run on UNIX systems. On ubuntu WSL, attempting to run the file will result in the following error :
```
-bash: ./setup.sh: /bin/sh^M: bad interpreter: No such file or directory
```

To correct this problem, one can run `dos2unix` to convert the line endings to `LF`, but this will change the file. Maybe an eslint rule can be added to enforce `LF` line endings, preventing such issues in the future ?

**Comment by benel** [comment]
This is really weird...
- CR/LF are usually [automatically handled by git](https://docs.github.com/fr/get-started/getting-started-with-git/configuring-git-to-handle-line-endings),
- I personally use macOS (hence with Unix endings) and not Windows,
- The shell script works fine on my zsh, and when I edit it on my computer with vi, I don't see the `DOS` flag associated with CRLF.

@raphaelweis 
Which version of git (Windows or Linux) do you use?
```sh
which git
```

What is your `autocrlf` setting?
```sh
git config --global core.autocrlf
```

**Comment by raphaelweis** [comment]
This is a mistake on my end, I tried accessing my repository on windows from my wsl instance, which means that git for windows had checked out the repo with CRLF including the `setup.sh` file.

Sorry for this mistake.

**Comment by benel** [comment]
> Sorry for this mistake.

No problem @raphaelweis. 
This discussion will be helpful for people experiencing the same problem :)
