### ISSUE TITLE
Included images should be sourced

### ISSUE THREAD

**Issue by Rochijr** [Hypertopic/HyperGlosae#21]
Lorsque plusieurs images sont présentes dans un document, les références dans la marge gauche se succèdent. Si on suppose un grand nombre d'images, cela pourrait manquer de visibilité et/ou de compréhension.

Il serait intéressant de pouvoir lier une image et sa référence (par le biais d'un titre, une légende ou de numérotations par exemple) pour rapidement et facilement faire le lien entre l'image et sa référence.

### Deliverables status

- [ ] Scenarios (Gherkin)
- [ ] Acceptance tests (Capybara)
- [ ]  Implementation strategy
- [ ] Implementation

**Comment by marina-pera** [comment]
La proposition que tu as faites n'est pas un changement que peux faire un personne. Cela n'est donc pas une "vrai" fonctionnalité.

**Comment by astrid-devericourt** [comment]
cette fonctionnalité ne respecte pas le critère d'indépendance, en effet il faudrait modifier à la fois les images et les commentaires. Elle n'est pas testable.

**Comment by benel** [comment]
> La proposition que tu as faites n'est pas un changement que peux faire un personne. Cela n'est donc pas une "vrai" fonctionnalité.

Exact @marina-pera. Ce serait plutôt un "fix" ergonomique...

**Comment by benel** [comment]
@Rochijr Comme c'est un fix (par rapport à quelque chose qui *devrait* se passer autrement), il faudrait construire un titre avec "should" dedans.

**Comment by benel** [comment]
In the @Hypertopic/histoire-de-l-art project, where many pictures will be included in collections, this fix will be really important.
Please note that the reference could be displayed as Bootstrap figure caption.

**Comment by MCtzr** [comment]
### Pour notre stratégie d'implémentation de ce ticket :

Nous pensons qu'il faut modifier le composant **Page**.

Nous remarquons que notre image est affichée dans le composant **Passage** à l’aide du composant **FormatedText** avec comme paramètre la variable **source**. Cette donnée correspond à l'adresse de notre image, qui est utilisée pour l'affichage de l'image via un _Markdown_. 
Nous pensons qu'il faudra modifier le composant **croppedImage**, qui permet de gérer les images à l'intérieur d'un _Markdown_. Ensuite, nous devrons modifier le **UseEffect** de content dans lequel le contenu du _Markdown_ est définit dans le composant **Page**. Il faudra donc qu'on modifie **source** (contenant l'adresse de l'image) pour lui ajouter sa légende. 

La légende est affichée dans les sources sur la gauche de la page. Nous avons pu voir qu'elle est contenue dans la constante **sourcesOfSourceMetaData** du composant **Page**.

Nous allons peut-être rencontrer des difficultés en transférant la légende de notre image contenue dans **sourcesOfSourceMetaData** vers notre fonction Passage pour ainsi l'afficher. Nous aurons aussi peut-être des difficultés à comprendre comment est définie la variable source.

Pour ce ticket, nous n'aurons pas besoin d'une bibliothèque particulière. Ce fix ne nécessite que de réorganiser les composants **Page** et **CroppedImage**. 

Finalement, nous avons modifié la fonction _getText()_ afin de pouvoir ajouter la légende de chaque image à la suite de son adresse au sein de chaque source. Nous avons ensuite pu modifier la composant **croppedImage** afin qu'il récupère à l'aide d'une _regexp_ la légende associée à chaque image, et puisse l'afficher en dessous de l'image au sein d'une balise HTML.
