### ISSUE TITLE
Add a function of styling with Markdown

### ISSUE THREAD

**Issue by cug-sun** [Hypertopic/HyperGlosae#22]
User can edit the document with Markdown. It's a docs-as-code approach, which allows a quick and easy authoring

**Comment by marina-pera** [comment]
This issue does not follow the "negotiable" of the criteria of INVEST because of the markdown.

**Comment by AmalCHIKHAOUI** [comment]
I think this issues could be two issues , first make the markdown and then allow the use it to edit

**Comment by benel** [comment]
@cug-sun Documents are already in markdown... 4eb7ef190b358c1fe7d8792bcca08dd60d570087
