### ISSUE TITLE
Add filters on the top to filter the comments that appear on the document

### ISSUE THREAD

**Issue by astrid-devericourt** [Hypertopic/HyperGlosae#23]
Cela permettrait de choisir dans quel ordre l'utilisateur veut voir apparaître les commentaires sur le document.

**Comment by julien-millour** [comment]
Cela n'est peut-être pas assez précis. 
Sur quelle information ordonner les documents? (Date de parution, auteur,...)

**Comment by CorentinPARZ** [comment]
Is it really useful to sort the comments for the user?

**Comment by benel** [comment]
> Is it really useful to sort the comments for the user? 

@astrid-devericourt @julien-millour I suggest indeed waiting for the problem to occur. Then, it will be easier to specify the filter criteria.

**Comment by benel** [comment]
Please rephrase it as a feature (the verb should be an action by the user).

**Comment by benel** [comment]
@astrid-devericourt Please note also that filtering and sorting are usually two **different** ways to focus on several elements of a list.
