### ISSUE TITLE
Mark articles that users have read by user himself

### ISSUE THREAD

**Issue by Ziwei-GONG-UTT** [Hypertopic/HyperGlosae#27]
modifier l'arrière-plan ou ajouter un marqueur de lecture aux articles que l'utilisateur a lus afin de conserver une meilleure trace de l'historique de lecture de l'utilisateur, à l'instar de l'existence des signets

**Comment by AmalCHIKHAOUI** [comment]
Ce ticket respecte les critères de INVEST

**Comment by benel** [comment]
@Ziwei-GONG-UTT You should make it clearer if the action is done by the user (for herself/himself) or if it is done automatically (for the user that is connected, or for all users).

**Comment by benel** [comment]
The scope is not clear enough for the ticket to be planned.
