### ISSUE TITLE
Create a document from scratch

### ISSUE THREAD

**Issue by MajedHL** [Hypertopic/HyperGlosae#28]
this feature allows users to create a document from scratch.

**Comment by AmalCHIKHAOUI** [comment]
Ce ticket respecte les critères de INVEST

**Comment by benel** [comment]
@MajedHL You may add "from scratch" in the title, so that its difference with #4 is clearer.

**Comment by lililiane** [comment]
Arts plastiques : ce cas d'usage permettre de rajouter des oeuvres

**Comment by RomainUTT** [comment]
Ethnométhodologie: This can be useful to start the entry point of a report.
