### ISSUE TITLE
Compare two articles

### ISSUE THREAD

**Issue by Ziwei-GONG-UTT** [Hypertopic/HyperGlosae#30]
Permettre aux utilisateurs de comparer deux articles, par exemple le nombre de lectures, de favoris, de commentaires, etc.

**Comment by benel** [comment]
@Ziwei-GONG-UTT Merci de reformuler le titre de manière à ce que ce soit une fonctionnalité (le verbe devrait être une action de l'utilisateur).

**Comment by benel** [comment]
While comparing documents is an important part of the product vision, I don't think that documents should be compared the way described in this ticket.
