### ISSUE TITLE
List all labels settable on documents

### ISSUE THREAD

**Issue by Rochijr** [Hypertopic/HyperGlosae#38]
This feature allows users to display and see all the labels that can be set on documents.

**Comment by benel** [comment]
Thank you for your suggestion @Rochijr.
However "displaying" is a system action, not a user action.
And please check that this feature complies with the INVEST criteria. It doesn't seem to.

**Comment by julien-millour** [comment]
This feature doesn't have any value now because it's already included in feature #43.

**Comment by antooinex** [comment]
Closing this issue for the following reason : duplicate of https://github.com/Hypertopic/HyperGlosae/issues/43
