### ISSUE TITLE
List all projects

### ISSUE THREAD

**Issue by CorentinPARZ** [Hypertopic/HyperGlosae#39]
List all [projects created](https://github.com/Hypertopic/HyperGlosae/issues/36)

Example: ![image](https://user-images.githubusercontent.com/126004011/225855595-5adc01fd-001c-438f-a442-6a637f1c7daf.png)

**Comment by benel** [comment]
While implemented in Cassandre, "diaries" (or "corpora" in the Hypertopic model or what you call "projects") are kind of "silos" and are not really compatible with "literature" as seen by Ted Nelson and then with the product vision. We will try to do emulate its benefits with an other model.
