### ISSUE TITLE
Create a referencing document from a previous document

### ISSUE THREAD

**Issue by StachoB** [Hypertopic/HyperGlosae#4]

**Comment by StachoB** [comment]
En tant qu'utilisateur depuis une page contenant un document, je souhaite pouvoir créer un nouveau document le référençant.

**Comment by vallhallalm** [comment]
To me this ticket seems to match INVEST method criteria so we can maybe validate it

**Comment by benel** [comment]
For a first implementation, the "link verb" (aka label) could be defaulted to "refersTo".
An updated feature could allow to chose between already used labels or even to define a new one.
