### ISSUE TITLE
Select a project to work on

### ISSUE THREAD

**Issue by CorentinPARZ** [Hypertopic/HyperGlosae#41]
From the [project list](https://github.com/Hypertopic/HyperGlosae/issues/39), select the project to work on. All documents created will be linked to this project

**Comment by benel** [comment]
While implemented in Cassandre, "diaries" (or "corpora" in the Hypertopic model or what you call "projects") are kind of "silos" and are not really compatible with "literature" as seen by Ted Nelson and then with the product vision. We will try to do emulate its benefits with an other model.
