### ISSUE TITLE
List all content linked to the selected project

### ISSUE THREAD

**Issue by CorentinPARZ** [Hypertopic/HyperGlosae#42]
After [selecting the project](https://github.com/Hypertopic/HyperGlosae/issues/41), we can see all documents in this project

**Comment by benel** [comment]
While implemented in Cassandre, "diaries" (or "corpora" in the Hypertopic model or what you call "projects") are kind of "silos" and are not really compatible with "literature" as seen by Ted Nelson and then with the product vision. We will try to do emulate its benefits with an other model.
