### ISSUE TITLE
Attach a predefined type to a document

### ISSUE THREAD

**Issue by RomainUTT** [Hypertopic/HyperGlosae#43]
This feature allows the user to attach a predefined type to a document

**Comment by DixOr51** [comment]
#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Mockups
- [ ] Implementation strategy
#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation
### Phase 3
- [ ] Screencast

**Comment by julien-millour** [comment]
We discussed this in the [Ethnométhodologie](https://github.com/orgs/Hypertopic/projects/44) group and came up with a mockup for this feature: 


Clicking the icon opens displays the type list allowing the user to change the document type.
![image](https://user-images.githubusercontent.com/126160064/231991228-dbcacf85-3fe4-4e65-b4b7-766a649d3753.png)

If the document already has a type, clicking on the type displays the list.

**Comment by RomainUTT** [comment]
Gherkin scenario we imagine:

**Fonctionnalité:** Attacher à un document

**Scénario:** un type qui est prédéfini 
  **Soit** une glose ouverte
  **Quand** j’attache le type “Interview” 
  **Alors** le type “Interview” est le type de la glose ouverte

**Comment by RomainUTT** [comment]
Implementation strategy we imagined: 


1. Create the acceptance tests (Capybara) 
2. Create a new component to select a type in a list
- Use a “list-group actionable items” component and “badges” component (https://react-bootstrap.github.io/components/list-group/#actionable-items) from React-Bootstrap dependency 
- Use [AiFillTag](https://react-icons.github.io/react-icons/search?q=aifilltag) icon from react-bootstrap-icons dependency
- Get the latest version of the document type from the database
- Update the type field (type) in the database with the function putDocument (inspired by the “Metadata” component)
4. Add this new component in the function DocumentCard in DocumentCard.js with type={doc} as properties.

**Comment by RomainUTT** [comment]
We assigned the work of this week, in the following way: 

Phase 2

-  Acceptance tests (Capybara) @julien-millour @Rochijr 

-  Implementation @DixOr51 @RomainUTT

**Comment by Rochijr** [comment]
Video of the feature:


https://user-images.githubusercontent.com/71018576/236425481-4e4114a9-5086-469f-8c6c-1b5f626289e5.mp4

**Comment by christophe-lejeune** [comment]
### Congratulations for the work done ! 

If you want to include types that are used into Cassandre into your example, fell free to read the following issue, authored by other students, some years ago : https://github.com/Hypertopic/Cassandre/issues/40

As you can read there, these types includes theoretical, operational, field, coding notes.

Perhaps, what follows relates to another feature... I however include this remark as an answer to your question about what I think of the feature. On the video, we can see (a) that typing is an option (a type can be attached, but an untyped document can also exist) and (b) that types are free (each document can be considered as the ground of another documents, whatever their respective types). 

In my view, types should guide the user : if I have a note on my research question, it will be the ground for an interview guide (and the platform indicates it). Once the guide is written, the next step will be to go on the field and to write a note about it, etc. 

Of course, you are creating HyperGlosae features (not Cassandre's ones)... Given you asked me what could encourage me to user HyperGlosae (in the perspective of making both tools closer), I take the liberty to indicate a gap with what I believe is relevant in the use of such a platform in an ethnographic perspective. 

I hope my comments will help you and I wish you the best for the last run ! 

Christophe

**Comment by benel** [comment]
> Of course, you are creating HyperGlosae features (not Cassandre's ones)... Given you asked me what could encourage me to user HyperGlosae (in the perspective of making both tools closer), I take the liberty to indicate a gap with what I believe is relevant in the use of such a platform in an ethnographic perspective.

Tel que je l'imagine, ce serait l'objet d'une future fonctionnalité :
on pourrait définir qu'il existe une transition recommandée entre "compte-rendu de terrain" et "compte-rendu de codage" et ainsi de suite.

Ainsi il suffirait de typer le premier document, puis on se laisserait guider comme dans Cassandre. Quand il n'y aurait qu'une seule transition recommandée, le document ancré serait typé automatiquement. Quand il y en a plusieurs, on nous recommanderait en priorité ceux-là.

**Comment by benel** [comment]
> Tel que je l'imagine, ce serait l'objet d'une future fonctionnalité 

See #113.

**Comment by benel** [comment]
Merged as PR #102.
