### ISSUE TITLE
Edit metadata describing a document

### ISSUE THREAD

**Issue by vallhallalm** [Hypertopic/HyperGlosae#5]
As a user I would like to include some metadata such as the title, the creator, the creation date ... to a document

**Comment by MCtzr** [comment]
Where you want to write these metadatas in the document? Instead of that, it's alright.

**Comment by vallhallalm** [comment]
@MCtzr Maybe it would not be negociable enough if we specify where we want them to be no ?

**Comment by lililiane** [comment]
Arts plastiques : ce cas d'usage peut permettre de décrire (nom, date, titre de l'oeuvre) d'un dessin/tableau ou même d'un collection/exposition.

**Comment by RomainUTT** [comment]
Ethnométhodologie: This can be helpful to describe our documents.
