### ISSUE TITLE
Include an existing image into an existing collection

### ISSUE THREAD

**Issue by lililiane** [Hypertopic/HyperGlosae#55]
#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation
### Phase 3
- [x] Screencast

**Comment by ShengjieZhou** [comment]
Fonctionnalité : Ajouter des images existantes à une collection

Scénario : une collection existante
Soit une image ouverte
Quand je l'inclus dans une collection 
Alors l'image "isGroundedIn" dans la collection

Mockups : 

![Image](https://github.com/Hypertopic/HyperGlosae/assets/125924846/8a27b811-754f-455d-9597-133295b53914)


Implementation strategy : 
1. Créer les tests d'acceptation
2. Réduire la largeur du bouton "+" sur la page
3. Ajouter un nouveau bouton
4. Modifier les icônes des deux boutons
5. Ajouter une liste de toutes les collections à la page
6. Mise à jour de "isGroundedIn" pour la donnée d'image "links"
7. Mise à jour de "includes" pour la donnée de la collection "links"

**Comment by benel** [comment]
Merci de créer un commit (dans une nouvelle branche) avec votre scénario.

**Comment by Ziwei-GONG-UTT** [comment]
PreView:
https://github.com/Hypertopic/HyperGlosae/assets/125918874/9cad7537-ec49-44da-b0d1-d43bc29bc969
