### ISSUE TITLE
Responsive design for phone

### ISSUE THREAD

**Issue by vallhallalm** [Hypertopic/HyperGlosae#59]
Adapt existing app so that it can be used on smaller screen devices like phones : Focus on displaying references and glose the right way.

**Comment by benel** [comment]
Thank you for your suggestion. 
For now it is still a bit vague. To be **estimable** and **testable**, you may add acceptance criteria...
Don't forget also to explain why this fix has **value** for @Hypertopic/histoire-de-l-art project.
