### ISSUE TITLE
Add a comment section on the right margin

### ISSUE THREAD

**Issue by AmalCHIKHAOUI** [Hypertopic/HyperGlosae#6]
The document is divided per section , each passage presents a section , the goal of this ticket is to create a comment section on the right margin that allows user to write a comment per passage 

![exemple](https://user-images.githubusercontent.com/93767067/221899939-b3aa6036-910c-47e2-82c0-8014232df869.PNG)

**Comment by vallhallalm** [comment]
This ticket seems to match INVEST method to me

**Comment by benel** [comment]
@AmalCHIKHAOUI How is related to #4? 
Since this "margin" seems to be a subtype of a "referencing document", when should we set this type? At creation? Or when the first passage is annotated. A benchmark between both solutions would probably necessary.

**Comment by benel** [comment]
@AmalCHIKHAOUI The title should probably be shortened up.

**Comment by RomainUTT** [comment]
Ethnométhodologie: This can be useful to describe more precisely an action performed.

**Comment by khbgbgk1** [comment]
Traduction 2024: Un commentaire pourrait permettre de préciser une spécification culturelle à un mot ou encore expliciter la raison d'un choix de traduction.

**Comment by PaulGitProject** [comment]
Traduction : 

Un commentaire pourrait permettre de préciser une spécification culturelle à un mot ou encore expliciter la raison d'un choix de traduction.
En plus de ce qui a été dit au dessus, un commentaire peut aussi permettre d’expliquer une traduction ou un passage dans un document.

**Comment by PaulGitProject** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/29106016/7880d5c4-a950-4f65-b63c-0b2e88706980)


![Image](https://github.com/Hypertopic/HyperGlosae/assets/29106016/e9e99f50-82b0-4128-9ec0-85e606d61f21)

**Comment by vernet-william** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/72734082/bf58d2bf-7f6d-44a8-beed-8764cb57b384)

**Comment by benel** [comment]
Not clear if the scope is the same as #156.
