### ISSUE TITLE
Create a defined visit

### ISSUE THREAD

**Issue by AmalCHIKHAOUI** [Hypertopic/HyperGlosae#60]
Créer un document qui présente un ensembles de références ordonnées à parcourir dans le but de faire ça en ordre

**Comment by AmalCHIKHAOUI** [comment]
Créer un document qui présente un ensembles de références ordonnées à parcourir dans le but de faire ça en ordre

**Comment by MCtzr** [comment]
This feature is already taken into account in : #95 .
