### ISSUE TITLE
Suggest related documents

### ISSUE THREAD

**Issue by AmalCHIKHAOUI** [Hypertopic/HyperGlosae#61]
Create an automatic suggestion for other documents related to the displayed one that other users could access them

**Comment by benel** [comment]
@AmalCHIKHAOUI Thank you for this feature suggestion.

> Suggest related documents
> Create an automatic suggestion for other documents related to the displayed one that other users could access them

Who does "suggest" or "create"?
Please remember that, in a feature title, the subject of the verb should be a user.

**Comment by MCtzr** [comment]
Is "Get an automatic suggestion of related documents" a better title?
