### ISSUE TITLE
Allow to alternate between image and text

### ISSUE THREAD

**Issue by AmalCHIKHAOUI** [Hypertopic/HyperGlosae#63]
Allow to alternate between a text and an image in the same document.

**Comment by benel** [comment]
Thank you @AmalCHIKHAOUI for your suggestion. Could you please elaborate on what you mean, give reasons for doing that and some examples?

**Comment by MCtzr** [comment]
The goal of this fix is to be able to add some text between 2 image-documents of a collection. Currently, the only way to do it is to add some text inside of the image document. But this solution is not interesting if we want to keep our image as a unique document.

Moreover, this fix is not adapted to our utilization of the collection. In our case, we navigate inside a collection document by document, so add a text document between two images of a collection will create another step in the "visit".

We could fix it by adding another verb inside each collection links, like "comment", to add some text inside which could be printed under our image (like the image presented below).


![Image](https://github.com/Hypertopic/HyperGlosae/assets/91234392/91f626c8-0986-48f7-9afe-a549cce83f8a)

**Comment by benel** [comment]
Mobile browsing should be kept out of the scope of this application (see #142).
