### ISSUE TITLE
Insert a video into a document

### ISSUE THREAD

**Issue by AVCharpentier** [Hypertopic/HyperGlosae#68]
Actuellement, une vidéo est jouée après que l'utilisateur soit redirigé suite à un clique sur une image présente dans un document, celle-ci doit être exécutable directement dans l'application. 

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Implementation strategy
#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation
### Phase 3
- [ ] Screencast

**Comment by benel** [comment]
Thank you for your suggestion @Hypertopic/histoire-du-cinema. 
Since Markdown is not supposed to handle videos, you should rephrase this fix as a feature.

**Comment by AVCharpentier** [comment]
Il est possible d'embarquer des vidéo youtube dans un document à l'aide du package suivant : 
- https://github.com/agentofuser/remark-oembed

L'utilisateur aurait donc a inscrire dans le document le lien d'accès de la vidéo youtube sur une nouvelle ligne et le plugins l'interprétera le lien de la vidéo écrit en markdown comme un iframe.

**Comment by AVCharpentier** [comment]
Comment sommes nous réparti actuellement ?

Capybara:
- Marina PERALTA FONSECA, 
- Antoine-Valentin CHARPENTIER

Implémentation:
- Agathe ALLIROL--BINET, 
- Astrid ROYER DE VERICOURT, 
- Sun SUN ,

**Comment by cug-sun** [comment]
As the documentation of [react-markdown](https://github.com/remarkjs/react-markdown#appendix-b-components) says, we can change the things that come from markdown. I tried like this:

- Edit the youtube video link in Markdown link syntax in a sample file
- In [FormattedText.js](https://github.com/Hypertopic/HyperGlosae/blob/main/frontend/src/FormattedText.js), add a key `a` in props `components` of `ReactMarkdown`, set its value with a custom method. 
- In custom method, replace the html element `<a>`  with `<iframe>`. To do this, define a regex to filter the youtube video id, and build the `iframe` 
![video demo](https://user-images.githubusercontent.com/57353828/235534395-944a6416-e48e-4f62-b4c1-28d07cce10eb.png)
