### ISSUE TITLE
Grant access to edit a document to a user

### ISSUE THREAD

**Issue by MCtzr** [Hypertopic/HyperGlosae#7]
**Description :** Permit the user to only modify his documents and the links inside only. Then permit the author to transmit his rights to a viewer.

**Acceptance criteria** : By default, the author is the only user capable to modify his document and its references inside. The author is also capable to give some rights to a viewer.

**Comment by StachoB** [comment]
Respecte tous les principes INVEST, peut être reformulé en tant que : Give access to edit a document to a user

**Comment by RomainUTT** [comment]
This ticket respects the principle of the INVEST method

**Comment by benel** [comment]
@MCtzr You could (or should?) rephrase the title with the verb "grant" (the sentence structure however is a bit different).

**Comment by MCtzr** [comment]
**Histoire de l'art** : Ce Ticket est une suggestion. Si par exemple on décide de prendre des features d'ajout ou de suppression de references d'un document (cf #2 et #3), il sera surement nécessaire de mettre en place une gestion des droits d'accès des utilisateurs.

**Comment by Anto792** [comment]
Traduction : this ticket can be useful in the futur

**Comment by AgatheIV** [comment]
Cela permettrait de choisir les utilisateurs qui pourraient apporter des éléments pertinents aux documents

**Comment by nitram35** [comment]
Cela faciliterait le travail collaboratif (dans le cas d'IF14 en binôme)

**Comment by Anto792** [comment]
[Maquette de Antonin DOMINGUEZ et Valentin KOELTGEN](https://www.figma.com/proto/tOV6vMWnpDldlhXUnwcBHF/Model?type=design&node-id=1-2&t=nRO46RsNYkhTBMqn-1&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A2&show-proto-sidebar=1&mode=design)


![Image](https://github.com/Hypertopic/HyperGlosae/assets/70704575/c56b6f55-3a41-4281-ac92-9c303bac2c7e)



![Image](https://github.com/Hypertopic/HyperGlosae/assets/70704575/482798ca-ea94-4ce5-9beb-c647d8096546)




![Image](https://github.com/Hypertopic/HyperGlosae/assets/70704575/f1bc555e-3aa2-46a5-a5e6-d5bba1c50950)

**Comment by petitfa1** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/115662302/2eec4bd0-41d8-4fa2-9d7a-c6c63be6b71c)



![Image](https://github.com/Hypertopic/HyperGlosae/assets/115662302/ad74efe5-f464-4e0c-993e-19f6e4318293)

**Comment by nitram35** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/105852593/8712e396-4269-49fc-ade6-6b8e69a08268)
![Image](https://github.com/Hypertopic/HyperGlosae/assets/105852593/6ee0567d-2f16-4d70-862d-8e7e69b57501)
![Image](https://github.com/Hypertopic/HyperGlosae/assets/105852593/14a4f172-6c56-40ab-a1cf-c3129da96acd)
![Image](https://github.com/Hypertopic/HyperGlosae/assets/105852593/0f910180-8c85-47cd-9b32-99240a76ac69)

**Comment by benel** [comment]
Thank you very much for your mockup. Was it peer work or single person work?

1. Auto-completion could probably moved to an another ticket. Because: 
    - There are a lot of design decisions to take (related to GDPR, projects, teams, etc.) and then a lot of cases to test.
    - This feature can work without it (think about INVEST criteria).
 2. Instead, it seems absolutely necessary to know **who is already an editor**. This is the minimum feedback and context awareness clues you need.

**Comment by petitfa1** [comment]
[IF05 Grant access doc.pdf](https://github.com/Hypertopic/HyperGlosae/files/15011485/IF05.Grant.access.doc.pdf)

**Comment by petitfa1** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/115662302/30ac6e1f-5ec3-4a6f-aa42-b6b083aab761)

**Comment by Barnabepetit** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/160789624/13135580-dbb3-4b7a-9a55-2d8c1e12d3ef)



![Image](https://github.com/Hypertopic/HyperGlosae/assets/160789624/f09d1fc6-bb6b-4cc9-a243-965cb2757c36)
![Image](https://github.com/Hypertopic/HyperGlosae/assets/160789624/411258fa-7384-4d2c-b58f-ed9f8a9c0dbd)

**Comment by Barnabepetit** [comment]
![Image](https://github.com/Hypertopic/HyperGlosae/assets/160789624/0b86ebd6-7d01-4a26-a397-6217478a9f2a)


![Image](https://github.com/Hypertopic/HyperGlosae/assets/160789624/bc0f8ea9-e7c9-464f-94ff-fc8129283ee3)



![Image](https://github.com/Hypertopic/HyperGlosae/assets/160789624/5390252c-731d-4452-8b2f-19215172a01a)

**Comment by Barnabepetit** [comment]
https://github.com/Hypertopic/HyperGlosae/assets/160789624/58bc08dc-a5ef-4080-bf04-eeb37723f13c

**Comment by Barnabepetit** [comment]
Raphaël WEIS collaborated as an expert on the scenarios in this ticket.

**Comment by benel** [comment]
Good evening @Barnabepetit!
Who was your peer when creating the screencast?
Or were you on your own?
