### ISSUE TITLE
React in real time to a video

### ISSUE THREAD

**Issue by AVCharpentier** [Hypertopic/HyperGlosae#73]
Un utilisateur doit être capable de réagir à une vidéo en temps réel. Cette réaction permettrait aux utilisateurs de réagir plus facilement sans devoir mettre en pause la vidéo et n'aura pas besoin d'écrire le timecode de la vidéo.

Les réactions peuvent être de différentes natures comme indiquer qu'un passage est marrant.

**Comment by benel** [comment]
This interesting feature seems to be similar to the main feature of [PolemicTweet](https://polemictweet.com).
However the reasons to integrate it with the existing features of Hyperglosae are still unclear.
