### ISSUE TITLE
Go to the video excerpt corresponding to a comment

### ISSUE THREAD

**Issue by GagatheRollex** [Hypertopic/HyperGlosae#74]
Avec cette fonctionnalité, les utilisateurs seront capable de faire une recherche sur des vidéos à partir de tag. En effet, il pourrons trouver les moments dans une vidéo qui auront été tagué auparavant.

Ainsi, en cliquant sur un timecode écrit dans un commentaire (document en glose), il pourra accéder directement au passage voulu de la vidéo, la vidéo avancera automatiquement au timecode désiré.  

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy

#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation

### Phase 3
- [x] Screencast

**Comment by AVCharpentier** [comment]
Scénario: Agathe & Astrid
Mockups: Marina & Antoine-Valentin
Stratégie d'implémentation: Sun

**Comment by AVCharpentier** [comment]
Mockup n°1

![Image](https://github.com/Hypertopic/HyperGlosae/assets/95986857/8d64db00-bffa-45be-a231-b194b3c14a9d)

**Comment by marina-pera** [comment]
Mockup n°2 

Lors du survole d'un timecode, un pop up apparaît indiquant "aller à ce timecode". L'utilisateur peut soit cliqué sur le timecode soit sur le popup pour aller à l'extrait.

![Image](https://github.com/Hypertopic/HyperGlosae/assets/71323084/f16ee915-c0e2-4187-a28c-a2887b89e454)

**Comment by AVCharpentier** [comment]
Mockup n°3

Tous les commentaires qui comportent un timecode, voit leur timecode remplacé par un bouton qui peut être cliqué par l'utilisateur pour accéder voulu. Lors du survol de celui-ci, son background peut changer.

![image](https://github.com/Hypertopic/HyperGlosae/assets/95986857/9f7e5d8a-c7cd-4dd6-9751-232c9693a210)

**Comment by AVCharpentier** [comment]
Mockup n°4:

Une petite icône (play) est présente à côté du timecode qui peut être cliqué dessus pour accéder au passage désiré.

![Image](https://github.com/Hypertopic/HyperGlosae/assets/95986857/515d5b63-8d58-4875-8340-72feecfd4e3b)


L'icône utilisé vient de flaticon:
https://www.flaticon.com/free-icon/play-button_375?term=play&page=1&position=3&origin=search&related_id=375
![Image](https://github.com/Hypertopic/HyperGlosae/assets/95986857/98a72c2d-b981-4ccb-aee3-777dccd8e732)

**Comment by cug-sun** [comment]
Implementation strategy

By embedding the start, end, and autoplay parameters in the YouTube link, a video excerpt can be played automatically.

To implement the video excerpt to play automatically after clicking the timestamp, we can use Web Vtt to specify the video excerpt.

For example:

00:01.000 --> 00:04.000
Never drink liquid nitrogen.

00:05.000 --> 00:09.000
It will perforate your stomach.
You could die.

**Comment by benel** [comment]
Merged as 7bee9f9.
