### ISSUE TITLE
#4 Create a referencing document from a video or audio file

### ISSUE THREAD

**Issue by vallhallalm** [Hypertopic/HyperGlosae#8]
As a user I would like to create a reference document from an audio or video file

**Comment by AmalCHIKHAOUI** [comment]
Ce ticket respecte les critères de INVEST

**Comment by benel** [comment]
@vallhallalm 
- This feature might be split in two features: one for video, one for audio. If not, you may explain why implementing one will also validate the other.
- If it is from the whole video, I suppose  #4 will already do that. I think you should mention fragment in the title and consider this as an enhancement of creating an annotation based on a text fragment.

**Comment by Dung3009** [comment]
Je pense que c'est une bonne idée parce qu'il y a plusieurs significations dans la vidéo pour créer un document
