### ISSUE TITLE
Create a collection from an existing image

### ISSUE THREAD

**Issue by lililiane** [Hypertopic/HyperGlosae#89]
#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation
### Phase 3
- [x] Screencast

Nos 2 propositions de maquettes sont : 

![Image](https://user-images.githubusercontent.com/125900085/232830835-cdab20c2-75e9-4bd7-bbda-97f28737260a.jpg)
![Image](https://user-images.githubusercontent.com/125900085/232830834-1ecfd24d-ef5c-4b12-851e-8de94e754d46.jpg)
![Image](https://user-images.githubusercontent.com/125900085/232830833-0f5136af-8d8b-4527-be29-d15520e92ae0.jpg)

Après discussion, nous décidons de choisir des boutons latéraux car d'une part la taille des icônes nous permet de diminuer et de les rendre plus visibles, d'une autre part les fonctionnalités des boutons sont complémentaires.

![Image](https://user-images.githubusercontent.com/125900085/232835086-fe8b3362-54f1-4d67-8970-f64740075719.jpg)
![Image](https://user-images.githubusercontent.com/125900085/232835087-d5b2d52a-3292-4fbd-a75d-3cee70f88a38.jpg)

Après avoir essayé différentes combinaisons d'icônes, nous choisissons le couple ci-dessous car il nous semble plus explicite et compréhensible.

![Image](https://user-images.githubusercontent.com/125900085/232835088-9779fca2-a2cb-44c7-992a-c089dc82c720.jpg)
![Image](https://user-images.githubusercontent.com/125900085/232833530-ab31dcfe-081e-4b0b-a59e-ee57a4f93bb5.PNG)

**Comment by lililiane** [comment]
Suite à la première réunion de suivi, nous avons réparti les tâches de la phase 1 :
- Scenarios (Gherkin) : Barbara et Liliane
- Implementation strategy Yichen et Shengjie

**Comment by LIUC2H5OH** [comment]
Implementation strategy

Créer de cas de test

- Réduire la largeur du bouton "Ajouter un commentaire" original 
- Créer un nouveau bouton sur le côté droit
- Modifier l'icône du bouton
- Ajouter une nouvelle valeur au champ isPartOf dans le fichier json correspondant à l'aide de la fonction putDocument
- Ajouter un nouveau fichier data json pour la nouvelle collection
- Mise à jour de la base de données

**Comment by StachoB** [comment]
**Scénarios :**
Fonctionnalité : create a collection from an existing image

Scénario : dans le cas d’une image dans une collection

Soit “1er Prix - Maroc” le document principal
Et le document fait partie de la collection “collection 2014”
Quand je crée une collection à partir de ce document
Alors une nouvelle collection est le document principal
Et “1er Prix - Maroc” est un document de la nouvelle collection
Et la description de “1er Prix - Maroc” s’affiche en légende de ce document

**Comment by lililiane** [comment]
Implementation est terminée : ZIwei et Liliane

**Comment by StachoB** [comment]
Preview : 
https://github.com/Hypertopic/HyperGlosae/assets/74101149/720cf3e0-487e-4310-b198-3f416177cee2
