### ISSUE TITLE
Navigate inside a collection

### ISSUE THREAD

**Issue by MCtzr** [Hypertopic/HyperGlosae#93]
The user should be able to directly go from an element of the collection to the next/last element.
The user should also be able to see where is he inside a collection (ex : 1/8), and the name of the collection.

The component could be similar to this example below.
![Image](https://user-images.githubusercontent.com/91234392/235666759-91327e4b-3221-49c2-bf55-0a79ea60b1ac.jpg)

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation
#### Phase 3
- [x] Screencast

**Comment by vallhallalm** [comment]
Voici le screencast de la feature en question : 


https://github.com/Hypertopic/HyperGlosae/assets/64600282/c141e7e5-501d-4175-863f-eead069fea3d

**Comment by benel** [comment]
Merci pour cette fonctionnalité @Hypertopic/histoire-de-l-art !
N'oubliez pas de faire une demande d'intégration.

**Comment by vallhallalm** [comment]
@benel [Here is the pull request](https://github.com/Hypertopic/HyperGlosae/pull/109)
