### ISSUE TITLE
Consult a collection on mobile device

### ISSUE THREAD

**Issue by SebBac** [Hypertopic/HyperGlosae#94]
Allow the user to consult a collection on a mobile device without showing the sources, the glosses, and the navbar, only focus on the content

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation
#### Phase 3
- [x] Screencast

Linked pull request : https://github.com/Hypertopic/HyperGlosae/pull/104

**Comment by MCtzr** [comment]
Screencast : 



https://github.com/Hypertopic/HyperGlosae/assets/91234392/239de7c6-e554-4d69-937c-b18ccf35a13e
