### ISSUE TITLE
Adapt the data samples for visit

### ISSUE THREAD

**Issue by kemplail** [Hypertopic/HyperGlosae#95]
Adapt the created data samples to illustrate the use case of a visit inside a church.

Pull request : https://github.com/Hypertopic/HyperGlosae/pull/98

**Comment by AmalCHIKHAOUI** [comment]
#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Mockups
- [ ] Implementation strategy
#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation
### Phase 3
- [ ] Screencast
