### ISSUE TITLE
Navigate between collections

### ISSUE THREAD

**Issue by vallhallalm** [Hypertopic/HyperGlosae#99]
Permit to know in which collection we are currently
Permit to switch between collection when we are on a document contained in multiple collection
Just on mobile devices

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation
#### Phase 3
- [x] Screencast

Related pull request : https://github.com/Hypertopic/HyperGlosae/pull/116

**Comment by benel** [comment]
Thank you for this suggestion @vallhallalm. 

When you write the scenario (with a `When` step), you will probably have to reword this feature. However, for now it is fine to identify what must be done.

**Comment by SebBac** [comment]
Sur téléphone, avec un menu ouvrant sur la gauche, il sera possible de voir la collection actuelle et d'accéder aux autres collections comprenant le document actuel.

![Image](https://github.com/Hypertopic/HyperGlosae/assets/73548842/d027eb32-3d63-422a-87a4-ccae551cd21d)

**Comment by benel** [comment]
Merci @SebBac et @AmalCHIKHAOUI pour cette maquette.

Quelques questions pour vous permettre de solidifier vos choix de conception :
- Comment le visiteur est-il prévenu qu'il y a d'autres parcours que le parcours actuel ?
- Comment ouvre-t-il ce menu ?
- Aviez-vous envisagé d'autres choix que ce volet escamotable ? Quelles sont les raisons du choix.

Merci d'avance.

**Comment by SebBac** [comment]
@benel 
Nous avons modifié notre maquette pour n'afficher que les autres parcours contenant le document actuel, cela se trouvera donc en fin de document

**Comment by SebBac** [comment]
Vidéo de présentation réalisé avec @AmalCHIKHAOUI : 

https://github.com/Hypertopic/HyperGlosae/assets/73548842/9cd770f3-8931-42b2-af36-d1c1c45623df

**Comment by SebBac** [comment]
Mise à jour de la vidéo de présentation :

https://github.com/Hypertopic/HyperGlosae/assets/73548842/b9167d90-7d12-4cfc-b699-084c777d8bb1

**Comment by benel** [comment]
Avez-vous transmis le screencast à votre PPP ?

**Comment by SebBac** [comment]
@MCtzr donné accès à notre partie prenante au Kaban afin qu'il puisse regarder, Adrien semble satisfait de ce que nous avons fait jusque là
